package io.github.javamodernizationlabs.jspecify.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.model.Dependency;
import org.apache.maven.model.Plugin;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.List;
import java.util.Locale;

/**
 * Implements the {@code jspecify-migration:nullaway-check} goal.
 *
 * <p>This goal verifies that the current Maven project exposes an executable Error Prone and
 * NullAway compiler setup and, when the check is enabled, generates a ready-to-use
 * {@code compilerArgs} snippet together with a Markdown status report in the configured output
 * directory. When the check is disabled, it writes only a {@code disabled} status report.
 */
@Mojo(name = "nullaway-check", threadSafe = true, requiresProject = true)
public class NullAwayCheckMojo extends AbstractMojo {

    /**
     * Creates a {@code NullAwayCheckMojo}.
     */
    public NullAwayCheckMojo() {
    }

    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    @Parameter(property = "jspecify.outputDirectory",
            defaultValue = "${project.build.directory}/reports/jml/jspecify")
    private File outputDirectory;

    @Parameter(property = "jspecify.nullaway.enabled", defaultValue = "true")
    private boolean enabled;

    @Parameter(property = "jspecify.nullaway.mode", defaultValue = "warn")
    private String mode;

    @Parameter
    private List<String> annotatedPackages;

    @Parameter
    private List<String> excludedClasses;

    /**
     * Runs the {@code jspecify-migration:nullaway-check} goal.
     *
     * <p>When the check is disabled, writes a {@code disabled} status report and returns. Otherwise
     * validates that annotated packages are configured and that the project provides an Error Prone
     * and NullAway compiler setup, then writes the generated compiler argument snippet and a
     * {@code ready} status report to the configured output directory.
     *
     * @throws MojoExecutionException if no annotated packages are configured, the project does not
     *     expose an executable Error Prone or NullAway setup, or the output cannot be written
     */
    @Override
    public void execute() throws MojoExecutionException {
        try {
            var out = outputDirectory.toPath();
            Files.createDirectories(out);
            if (!enabled) {
                Files.writeString(out.resolve("nullaway-check.md"),
                        "# JSpecify NullAway check\n\nStatus: `disabled`\n",
                        StandardCharsets.UTF_8);
                getLog().info("JSpecify NullAway check disabled.");
                return;
            }
            List<String> packages = annotatedPackages == null ? List.of() : annotatedPackages;
            List<String> excluded = excludedClasses == null ? List.of() : excludedClasses;
            if (packages.isEmpty()) {
                throw new MojoExecutionException("JSpecify NullAway profile is enabled but no "
                        + "annotatedPackages are configured.");
            }
            String compilerConfig = compilerPluginConfiguration();
            boolean errorProneConfigured = compilerConfig.toLowerCase(Locale.ROOT)
                    .contains("errorprone")
                    || compilerConfig.toLowerCase(Locale.ROOT).contains("-xep:")
                    || hasDependency("error_prone");
            boolean nullAwayConfigured = compilerConfig.toLowerCase(Locale.ROOT)
                    .contains("nullaway")
                    || hasDependency("nullaway");
            if (!errorProneConfigured || !nullAwayConfigured) {
                throw new MojoExecutionException("JSpecify NullAway profile is enabled but the "
                        + "project does not expose an executable Maven Compiler "
                        + "Error Prone/NullAway setup.");
            }
            String snippet = """
                    <!-- Generated by JSpecify Migration Kit. -->
                    <compilerArgs>
                      <arg>-XepOpt:NullAway:AnnotatedPackages=%s</arg>
                      <arg>-XepOpt:NullAway:ExcludedClasses=%s</arg>
                      <arg>-Xep:NullAway:%s</arg>
                    </compilerArgs>
                    """.formatted(
                    String.join(",", packages),
                    String.join(",", excluded),
                    mode.equalsIgnoreCase("error") ? "ERROR" : "WARN");
            Files.writeString(out.resolve("nullaway-maven.xml"), snippet, StandardCharsets.UTF_8);
            String report = """
                    # JSpecify NullAway check

                    Status: `ready`
                    Error Prone configured: `%s`
                    NullAway configured: `%s`
                    Mode: `%s`
                    Annotated packages: `%s`
                    Excluded classes: `%s`
                    """.formatted(errorProneConfigured, nullAwayConfigured, mode,
                    String.join(",", packages), String.join(",", excluded));
            Files.writeString(out.resolve("nullaway-check.md"), report, StandardCharsets.UTF_8);
            getLog().info("JSpecify NullAway Maven profile verified; config written to " + out);
        } catch (Exception e) {
            if (e instanceof MojoExecutionException mojoExecutionException) {
                throw mojoExecutionException;
            }
            throw new MojoExecutionException("JSpecify NullAway config failed: " + e.getMessage(), e);
        }
    }

    private String compilerPluginConfiguration() {
        if (project == null || project.getBuildPlugins() == null) {
            return "";
        }
        return project.getBuildPlugins().stream()
                .filter(plugin -> "maven-compiler-plugin".equals(plugin.getArtifactId()))
                .map(Plugin::getConfiguration)
                .map(configuration -> configuration == null ? "" : configuration.toString())
                .findFirst()
                .orElse("");
    }

    private boolean hasDependency(String token) {
        String lower = token.toLowerCase(Locale.ROOT);
        if (project == null) {
            return false;
        }
        boolean projectDependency = project.getDependencies().stream()
                .anyMatch(dependency -> dependencyMatches(dependency, lower));
        boolean pluginDependency = project.getBuildPlugins().stream()
                .flatMap(plugin -> plugin.getDependencies().stream())
                .anyMatch(dependency -> dependencyMatches(dependency, lower));
        return projectDependency || pluginDependency;
    }

    private boolean dependencyMatches(Dependency dependency, String lowerToken) {
        return containsIgnoreCase(dependency.getGroupId(), lowerToken)
                || containsIgnoreCase(dependency.getArtifactId(), lowerToken);
    }

    private boolean containsIgnoreCase(String value, String lowerToken) {
        return value != null && value.toLowerCase(Locale.ROOT).contains(lowerToken);
    }
}
