package io.github.javamodernizationlabs.jspecify.cli;

import io.github.javamodernizationlabs.jspecify.config.JspecifyConfig;
import io.github.javamodernizationlabs.jspecify.config.JspecifyConfigLoader;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.Callable;

/**
 * The {@code nullaway-config} command, which generates NullAway and Error Prone
 * configuration snippets for a project.
 *
 * <p>It produces a Gradle Kotlin DSL block that configures NullAway for the project rooted at
 * {@code --project}, using the check severity implied by {@code --mode}, the annotated
 * packages from {@code --annotated-packages} and the exclusions from
 * {@code --excluded-classes}. The snippet is written to {@code nullaway.gradle.kts} under the
 * directory selected by {@code --output-dir}; when {@code --apply} is given the block is also
 * merged into the project's {@code build.gradle.kts}.</p>
 */
@Command(
        name = "nullaway-config",
        description = "Generate NullAway/Error Prone configuration snippets.",
        mixinStandardHelpOptions = true
)
public class NullAwayConfigCommand implements Callable<Integer> {

    /**
     * Creates a {@code NullAwayConfigCommand}.
     */
    public NullAwayConfigCommand() {
    }

    @Option(names = {"--project"}, defaultValue = ".") Path project;
    @Option(names = {"--mode"}) String mode;
    @Option(names = {"--annotated-packages"}, split = ",") List<String> annotatedPackages;
    @Option(names = {"--excluded-classes"}, split = ",") List<String> excludedClasses;
    @Option(names = {"--apply"}, description = "Apply the generated Gradle Kotlin DSL block when possible.")
    boolean apply;
    @Option(names = {"--output-dir"}) Path output;

    /**
     * Generates the NullAway Gradle snippet, writes it to disk and optionally merges it into
     * the project build file.
     *
     * @return the process exit code; always {@code 0} on successful generation
     * @throws Exception if loading the project configuration or writing the snippet fails
     */
    @Override
    public Integer call() throws Exception {
        Path projectRoot = project.toAbsolutePath().normalize();
        JspecifyConfig config = JspecifyConfigLoader.load(projectRoot);
        Path out = output == null
                ? config.resolveReportsOutputDirectory(projectRoot)
                : output.toAbsolutePath().normalize();
        Files.createDirectories(out);
        String effectiveMode = mode == null || mode.isBlank() ? config.nullawayMode() : mode;
        String normalizedMode = effectiveMode.trim().toLowerCase(Locale.ROOT);
        if (!normalizedMode.equals("warn") && !normalizedMode.equals("error")) {
            System.err.println("Unsupported NullAway mode: " + effectiveMode
                    + ". Expected warn or error.");
            return 2;
        }
        String severity = normalizedMode.equals("error") ? "ERROR" : "WARN";
        List<String> packages = annotatedPackages == null
                ? config.nullawayAnnotatedPackages()
                : annotatedPackages;
        List<String> excluded = excludedClasses == null
                ? config.nullawayExcludedClasses()
                : excludedClasses;
        if (packages.stream().map(String::trim).filter(s -> !s.isBlank()).toList().isEmpty()) {
            System.err.println("NullAway annotated packages are required. Configure "
                    + "nullaway.annotatedPackages or pass --annotated-packages.");
            return 2;
        }
        String snippet = """
                // Generated by JSpecify Migration Kit.
                tasks.withType(JavaCompile).configureEach {
                    options.errorprone {
                        option("NullAway:AnnotatedPackages", "%s")
                        option("NullAway:ExcludedClasses", "%s")
                        check("NullAway", CheckSeverity.%s)
                    }
                }
                """.formatted(
                String.join(",", packages.stream().map(String::trim)
                        .filter(s -> !s.isBlank()).toList()),
                String.join(",", excluded),
                severity);
        Files.writeString(out.resolve("nullaway.gradle.kts"), snippet, StandardCharsets.UTF_8);
        if (apply) {
            applyGradleSnippet(projectRoot, snippet);
        }
        System.out.println("NullAway config written to " + out);
        return 0;
    }

    private void applyGradleSnippet(Path projectRoot, String snippet) throws Exception {
        Path buildFile = projectRoot.resolve("build.gradle.kts");
        if (!Files.isRegularFile(buildFile)) {
            return;
        }
        String start = "// BEGIN JSpecify Migration Kit NullAway";
        String end = "// END JSpecify Migration Kit NullAway";
        String block = "\n" + start + "\n" + snippet + end + "\n";
        String current = Files.readString(buildFile, StandardCharsets.UTF_8);
        int startIndex = current.indexOf(start);
        int endIndex = current.indexOf(end);
        String updated = current;
        if (startIndex >= 0 && endIndex > startIndex) {
            updated = current.substring(0, startIndex).stripTrailing()
                    + block
                    + current.substring(endIndex + end.length());
        } else {
            updated = current.stripTrailing() + block;
        }
        Files.writeString(buildFile, updated, StandardCharsets.UTF_8);
    }
}
